spring:
  profiles:
    active: dev

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        default_schema:
  datasource:
    url: jdbc:mysql://localhost:3306/pepsbook?serverTimezone=Europe/Moscow&useUnicode=yes&characterEncoding=UTF-8
    username: myuser
    password: motamota

---

spring:
  profiles: dev
  #to not cache thymeleaf pages when dev
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

---

spring:
  profiles: tst
  datasource:
    url: jdbc:h2:mem:pepsbook;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
my:
  tst:
    headless: true
    closeBrowser: true
    monkey:
      seed: 0
      rounds: 10
      steps:  30
