spring:
  profiles:
    active: dev

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/pepsbook?serverTimezone=Europe/Moscow&useUnicode=yes&characterEncoding=UTF-8
    username: myuser
    password: motamota
  cache:
    #possible: ehcache,redis,none
    type: redis
    redis:
      key-prefix: "pb-cache::"
      time-to-live: 86400000
  session:
    redis:
      #otherwise reconnect doesnt't work
      cleanup-cron: "*/1 * * * * *"
  redis:
    host: localhost
jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: and0LWI2NC1zZWNyZXQta2V5LXNlY3JldC1zZWNyZXQtc2VjcmV0LWtleS1rZS1rdS1rdS1rdS1rdS1rdS1rdS1rZS1rZXkK
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh
my:
  mindsPageSize: 10
  paginatorMaxSize: 12
  paginatorWide: 3
  #should be more than 1 min. Otherwise cleanup-cron won't have time to kill the old session
  time2RetryUseRedis: 70000

---

spring:
  profiles: dev
#to not cache thymeleaf pages when dev
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  resources:
    static-locations: file:src/main/resources/static
#  redis:
#    host: 192.168.1.105

---

spring:
  profiles: tst-simple
my:
  mindsPageSize: 2
  paginatorMaxSize: 8
  paginatorWide: 1

---

spring:
  profiles: tst
  datasource:
    url: jdbc:h2:mem:pepsbook;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
my:
  tst:
    strict: false
    checkRenders: true
    headless: false
    closeBrowser: true
    monkey:
      feignDB:
        enabled: random
        users: 30
        friendships: 60
        minds: 200
        answers: 300

      seeds: 0
      #2,2,2,3,3,3
      rounds: 10
      steps:  100
      failImmediately: false
