spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema:
  datasource:
    url: jdbc:mysql://localhost:3306/pepsbook?serverTimezone=Europe/Moscow&useUnicode=yes&characterEncoding=UTF-8
    username: myuser
    password: motamota
